# fly.toml app configuration file generated for inctagram-api on 2023-06-28T13:12:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "inctagram-api"
primary_region = "waw"

[processes]
  api-gateway = "node dist/apps/api-gateway/src/main"
  auth-microservice = "node dist/apps/auth/src/main"

app = "inctagram-api"
primary_region = "waw"

[processes]
  api-gateway = "node dist/apps/api-gateway/src/main"
  auth-microservice = "node dist/apps/auth/src/main"

[[services]]
  http_checks = []
  internal_port = 5000
  processes = ["api-gateway"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"


[[services]]
  http_checks = []
  internal_port = 5001
  processes = ["auth-microservice"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 50
    soft_limit = 25
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"





